// ========================================================
// FlowArchitect - XML Generation Engine v2
// ========================================================
// Generates mxGraph XML with precise x,y positioning.
// No reliance on Draw.io's auto-layout.
// ========================================================


const STENCILS = {
    ...SF_STENCILS, // Autogenerated Snowflake stencils from v5 pack
    ...typeof FABRIC_STENCILS !== 'undefined' ? FABRIC_STENCILS : {}, // Autogenerated Fabric stencils from v6 pack
    // ---- Fabric Aliases & Fixes ----
    'fab_activator': (typeof FABRIC_STENCILS !== 'undefined' ? FABRIC_STENCILS['fab_digital_twin_builder_activator'] : null),
    'fab_real_time_dashboard': (typeof FABRIC_STENCILS !== 'undefined' ? FABRIC_STENCILS['fab_dashboard'] : null),
    'fab_real_time_intelligence': (typeof FABRIC_STENCILS !== 'undefined' ? FABRIC_STENCILS['fab_real_time_intelligence'] : null),
    // ---- Snowflake Aliases & Fixes ----
    'sf_copilot': (typeof SF_STENCILS !== 'undefined' ? SF_STENCILS['sf_snowflake_copilot'] : null),
    'sf_horizon': (typeof SF_STENCILS !== 'undefined' ? SF_STENCILS['sf_secure_data'] : null),
    'sf_dynamic_tables': (typeof SF_STENCILS !== 'undefined' ? SF_STENCILS['sf_iceberg_tables'] : null),
    'sf_streamlit': (typeof SF_STENCILS !== 'undefined' ? SF_STENCILS['sf_application'] : null),
    'sf_snowpipe': (typeof SF_STENCILS !== 'undefined' ? SF_STENCILS['sf_data_engineering'] : null),
    // ---- Structural ----
    'zone': {
        style: 'rounded=1;whiteSpace=wrap;html=1;fillColor=#E6F2E6;strokeColor=#82b366;fontColor=#333333;fontSize=11;fontStyle=1;verticalAlign=top;spacingTop=5;',
        w: 'auto', h: 'auto'
    },
    'zone_blue': {
        style: 'rounded=1;whiteSpace=wrap;html=1;fillColor=#DAE8FC;strokeColor=#6c8ebf;fontColor=#333333;fontSize=11;fontStyle=1;verticalAlign=top;spacingTop=5;',
        w: 'auto', h: 'auto'
    },
    'governance_bar': {
        style: 'rounded=0;whiteSpace=wrap;html=1;fillColor=#f5f5f5;strokeColor=#cccccc;fontColor=#333333;fontSize=10;fontStyle=0;align=center;verticalAlign=middle;',
        w: 'auto', h: 35
    },
    // ---- Data Sources ----
    'data_source': {
        style: 'rounded=0;whiteSpace=wrap;html=1;fillColor=#ffffff;strokeColor=#333333;fontColor=#333333;fontSize=11;align=center;verticalAlign=middle;',
        w: 120, h: 45
    },
    // ---- Azure Services ----
    'adf':            { style: imgStyle('azure2/databases/Data_Factory.svg'),                  w: 48, h: 48 },
    'databricks':     { style: imgStyle('azure2/analytics/Azure_Databricks.svg'),              w: 48, h: 55 },
    'event_hubs':     { style: imgStyle('azure2/iot/Event_Hubs.svg'),                          w: 48, h: 48 },
    'cosmos_db':      { style: imgStyle('azure2/databases/Azure_Cosmos_DB.svg'),               w: 48, h: 48 },
    'azure_sql':      { style: imgStyle('azure2/databases/SQL_Database.svg'),                  w: 48, h: 48 },
    'powerbi':        { style: imgStyle('azure2/power_platform/PowerBI.svg'),                  w: 48, h: 55 },
    'synapse':        { style: imgStyle('azure2/analytics/Azure_Synapse_Analytics.svg'),       w: 48, h: 48 },
    'stream_analytics': { style: imgStyle('azure2/analytics/Stream_Analytics_Jobs.svg'),       w: 48, h: 48 },
    'purview':        { style: imgStyle('azure2/databases/Azure_Purview_Accounts.svg'),        w: 48, h: 48 },
    'data_catalog':   { style: imgStyle('azure2/integration/Azure_Data_Catalog.svg'),          w: 48, h: 48 },
    'adls':           { style: imgStyle('azure2/storage/Data_Lake_Storage_Gen1.svg'),          w: 48, h: 48 },
    'azure_monitor':  { style: imgStyle('azure2/management_governance/Monitor.svg'),           w: 48, h: 48 },
    'web_app':        { style: imgStyle('azure2/app_services/App_Services.svg'),               w: 48, h: 48 },
    'storage_account':{ style: imgStyle('azure2/storage/Storage_Accounts.svg'),              w: 48, h: 48 },
    'key_vault':      { style: imgStyle('azure2/security/Key_Vaults.svg'),                   w: 48, h: 48 },
    'active_directory':{ style: imgStyle('azure2/identity/Azure_Active_Directory.svg'),      w: 48, h: 48 },
    'kafka':          { style: imgStyle('azure2/iot/Event_Hubs.svg'),                          w: 48, h: 48 },
    // ---- Boundaries ----
    'boundary_vnet': {
        style: 'rounded=1;whiteSpace=wrap;html=1;fillColor=#f8fbff;strokeColor=#0078D4;strokeWidth=2;dashed=1;fontColor=#333333;fontSize=11;fontStyle=1;verticalAlign=top;spacingTop=5;',
        w: 'auto', h: 'auto'
    },
    'boundary_subnet': {
        style: 'rounded=1;whiteSpace=wrap;html=1;fillColor=#ffffff;strokeColor=#cccccc;strokeWidth=1;fontColor=#333333;fontSize=11;fontStyle=1;verticalAlign=top;spacingTop=5;',
        w: 'auto', h: 'auto'
    },
    'boundary_rg': {
        style: 'rounded=1;whiteSpace=wrap;html=1;fillColor=none;strokeColor=#005ba1;strokeWidth=2;fontColor=#333333;fontSize=11;fontStyle=1;verticalAlign=top;spacingTop=5;',
        w: 'auto', h: 'auto'
    },
    'boundary_generic': {
        style: 'rounded=1;whiteSpace=wrap;html=1;fillColor=none;strokeColor=#999999;strokeWidth=2;dashed=1;fontColor=#333333;fontSize=11;fontStyle=1;verticalAlign=top;spacingTop=5;',
        w: 'auto', h: 'auto'
    },
    // ---- Storage layers ----
    'bronze_layer': {
        style: 'rounded=1;whiteSpace=wrap;html=1;fillColor=#FFF2CC;strokeColor=#D6B656;fontColor=#333333;fontSize=11;fontStyle=1;align=center;verticalAlign=middle;',
        w: 120, h: 45
    },
    'silver_layer': {
        style: 'rounded=1;whiteSpace=wrap;html=1;fillColor=#E1D5E7;strokeColor=#9673A6;fontColor=#333333;fontSize=11;fontStyle=1;align=center;verticalAlign=middle;',
        w: 120, h: 45
    },
    'gold_layer': {
        style: 'rounded=1;whiteSpace=wrap;html=1;fillColor=#D5E8D4;strokeColor=#82B366;fontColor=#333333;fontSize=11;fontStyle=1;align=center;verticalAlign=middle;',
        w: 120, h: 45
    },
    // ---- Tools (no Azure icon) ----
    'tool': {
        style: 'rounded=1;whiteSpace=wrap;html=1;fillColor=#ffffff;strokeColor=#666666;fontColor=#333333;fontSize=10;align=center;verticalAlign=middle;',
        w: 70, h: 35
    },
    'consumer': {
        style: 'rounded=1;whiteSpace=wrap;html=1;fillColor=#f0f0f0;strokeColor=#999999;fontColor=#333333;fontSize=10;align=center;verticalAlign=middle;',
        w: 130, h: 40
    },
    // ---- Fallback ----
    'default': {
        style: 'rounded=1;whiteSpace=wrap;html=1;fillColor=#ffffff;strokeColor=#a6a6a6;fontColor=#333333;fontSize=11;',
        w: 120, h: 50
    }
};

// Layout constants (pixels)
const L = {
    leftMargin: 30,
    sourceColW: 140,   // width for the source column (col -1)
    phaseColW: 155,    // width per phase column
    headerY: 10,       // y of phase header labels
    headerH: 28,       // height of header labels
    contentY: 50,      // y start for first content row
    rowH: 100          // vertical spacing between rows
};

// ---- Draw.io iframe communication ----
const iframe = document.getElementById('drawio-iframe');
let iframeReady = false;

window.addEventListener('message', function(evt) {
    if (evt.data && evt.data.length > 0) {
        try {
            const msg = JSON.parse(evt.data);
            if (msg.event === 'init') {
                iframeReady = true;
                console.log('Draw.io iframe ready (init event received)');
                document.getElementById('renderBtn').textContent = 'Render Diagram';
            }
        } catch (e) {}
    }
});

// Fallback: if init event not received after 12s, force ready
setTimeout(() => {
    if (!iframeReady) {
        console.warn('Draw.io init timeout — forcing ready state');
        iframeReady = true;
        document.getElementById('renderBtn').textContent = 'Render Diagram';
    }
}, 12000);

// ---- UI Micro-interactions ----
const syncStatus = document.getElementById('sync-status');
let syncTimeout;

document.getElementById('csvInput').addEventListener('input', () => {
    if (syncStatus) {
        syncStatus.textContent = '● SYNCING...';
        syncStatus.style.color = '#fbbf24'; // Amber
        clearTimeout(syncTimeout);
        syncTimeout = setTimeout(() => {
            syncStatus.textContent = '● SYNCED';
            syncStatus.style.color = '#10b981'; // Emerald
        }, 800);
    }
});

document.getElementById('renderBtn').addEventListener('click', function() {
    if (!iframeReady) {
        alert('FlowArchitect Engine is still initializing. Please wait.');
        return;
    }
    const csv = document.getElementById('csvInput').value.trim();
    if (!csv) return;

    // Visual feedback
    this.style.transform = 'scale(0.95)';
    setTimeout(() => this.style.transform = 'scale(1)', 100);

    try {
        const xml = buildDiagram(csv);
        iframe.contentWindow.postMessage(JSON.stringify({
            action: 'load',
            autosave: 1,
            xml: xml
        }), '*');
        
        // Success glow
        this.style.boxShadow = '0 0 30px #38bdf8';
        setTimeout(() => this.style.boxShadow = '0 0 15px rgba(56, 189, 248, 0.3)', 1000);
    } catch (err) {
        console.error('Diagram generation error:', err);
        alert('Logic Error: ' + err.message);
    }
});

// ---- Info Modal Management ----
function openInfoModal(title, htmlContent, isCode = false, copyText = null) {
    const modal = document.getElementById('infoModal');
    const body = document.getElementById('infoBody');
    const titleEl = document.getElementById('infoTitle');
    const copyBtn = document.getElementById('infoCopyBtn');

    titleEl.textContent = title;
    body.innerHTML = isCode ? `<pre id="promptText">${htmlContent}</pre>` : `<p>${htmlContent}</p>`;
    
    if (copyText) {
        copyBtn.style.display = 'block';
        copyBtn.onclick = () => {
            navigator.clipboard.writeText(copyText);
            const originalText = copyBtn.textContent;
            copyBtn.textContent = '✅ Copied!';
            setTimeout(() => copyBtn.textContent = originalText, 2000);
        };
    } else {
        copyBtn.style.display = 'none';
    }

    modal.classList.add('active');
}

function closeModals() {
    document.getElementById('infoModal').classList.remove('active');
    document.getElementById('xmlModal').classList.remove('active');
}

document.getElementById('closeInfoModal').addEventListener('click', closeModals);
document.getElementById('closeModal').addEventListener('click', closeModals);

window.addEventListener('click', (e) => {
    if (e.target.classList.contains('modal-overlay')) closeModals();
});

// ---- Workflow Step Actions ----
document.getElementById('step-1').addEventListener('click', () => {
    const promptText = document.getElementById('prompt-storage').textContent || "No prompt available. Rebuild tool.";
    openInfoModal("System Prompt (v2)", promptText, true, promptText);
});

document.getElementById('step-2').addEventListener('click', () => {
    openInfoModal("LLM Instructions", `
        1. Copy the <b>System Prompt</b> from Step 1.<br><br>
        2. Open your preferred LLM (Claude, Gemini, or Copilot) in a separate tab.<br><br>
        3. Paste the prompt, followed by your <b>Architecture Description</b> in plain English.<br><br>
        4. Copy the resulting CSV block back into the <b>CSV SOURCE</b> console here.
    `);
});

document.getElementById('step-3').addEventListener('click', () => {
    document.getElementById('csvInput').focus();
});

document.getElementById('step-4').addEventListener('click', () => {
    document.getElementById('renderBtn').click();
});

document.getElementById('step-5').addEventListener('click', () => {
    window.open('https://app.diagrams.net', '_blank');
});

// ---- Copy XML — show in modal for manual copy ----
document.getElementById('copyXmlBtn').addEventListener('click', () => {
    const csv = document.getElementById('csvInput').value.trim();
    if (!csv) { alert('No CSV data to convert.'); return; }

    try {
        const xml = buildDiagram(csv);
        const modal = document.getElementById('xmlModal');
        const output = document.getElementById('xmlOutput');
        output.value = xml;
        modal.classList.add('active');
        output.focus();
        output.select();
    } catch (err) {
        alert('Error: ' + err.message);
    }
});

// XML Copy Button logic
if (document.getElementById('xmlCopyBtn')) {
    document.getElementById('xmlCopyBtn').addEventListener('click', () => {
        const xml = document.getElementById('xmlOutput').value;
        navigator.clipboard.writeText(xml);
        const btn = document.getElementById('xmlCopyBtn');
        const originalText = btn.textContent;
        btn.textContent = '✅ Copied!';
        setTimeout(() => btn.textContent = originalText, 2000);
    });
}

// ============================================================
// Main diagram builder: CSV → mxGraph XML
// ============================================================
function buildDiagram(csvText) {
    // --- 1. Parse CSV ---
    const NL = String.fromCharCode(10);
    const lines = csvText.split(NL).filter(l => l.trim());
    const hdrs = lines[0].split(',').map(h => h.trim());
    const idx = name => hdrs.indexOf(name);

    const allNodes = [];
    const byId = {};

    for (let i = 1; i < lines.length; i++) {
        const vals = csvSplit(lines[i]);
        const n = {
            id:            (vals[idx('id')]            || '').trim(),
            name:          (vals[idx('name')]          || '').trim(),
            parent:        (vals[idx('parent')]        || '').trim(),
            type:          (vals[idx('type')]          || '').trim(),
            receives_from: (vals[idx('receives_from')] || '').trim(),
            step_number:   (vals[idx('step_number')]   || '').trim()
        };
        allNodes.push(n);
        byId[n.id] = n;
    }

    // --- 2. Separate phases from content ---
    const phases = allNodes.filter(n => n.type === 'phase');
    const boundaries = allNodes.filter(n => n.type.startsWith('boundary'));
    const content = allNodes.filter(n => n.type !== 'phase' && !n.type.startsWith('boundary'));
    const phaseIdx = {};
    phases.forEach((p, i) => { phaseIdx[p.id] = i; });

    // --- 3. Build edge list ---
    const edges = [];
    content.forEach(n => {
        if (!n.receives_from) return;
        n.receives_from.split(';').forEach(srcId => {
            srcId = srcId.trim();
            if (srcId && byId[srcId]) {
                edges.push({ from: srcId, to: n.id, step: n.step_number });
            }
        });
    });

    function getPhaseId(nodeId) {
        let n = byId[nodeId];
        while (n && n.type !== 'phase' && n.parent) {
            n = byId[n.parent];
        }
        return n && n.type === 'phase' ? n.id : null;
    }

    // --- 4. Assign columns ---
    content.forEach(n => {
        const pId = getPhaseId(n.id);
        if (pId && phaseIdx[pId] !== undefined) {
            n._col = phaseIdx[pId];
        } else if (!n.receives_from) {
            n._col = -1;
        }
    });

    for (let iter = 0; iter < 20; iter++) {
        let changed = false;
        content.forEach(n => {
            if (n._col !== undefined) return;
            const srcs = n.receives_from.split(';').map(s => s.trim()).filter(Boolean);
            const cols = srcs.map(s => byId[s]?._col).filter(c => c !== undefined);
            if (cols.length > 0) {
                n._col = Math.max(...cols) + 1;
                changed = true;
            }
        });
        if (!changed) break;
    }
    content.forEach(n => { if (n._col === undefined) n._col = phases.length; });

    // --- 5. Assign rows within each column ---
    const colBuckets = {};
    content.forEach(n => {
        const c = n._col;
        if (!colBuckets[c]) colBuckets[c] = [];
        colBuckets[c].push(n);
    });
    Object.values(colBuckets).forEach(bucket => {
        bucket.forEach((n, i) => { n._row = i; });
    });

    // Align source nodes (col -1) to their target's row
    // When multiple sources feed the same target, offset them vertically
    if (colBuckets[-1]) {
        const usedRows = new Set();
        colBuckets[-1].forEach(src => {
            const tgtEdge = edges.find(e => e.from === src.id);
            if (tgtEdge && byId[tgtEdge.to]?._row !== undefined) {
                let targetRow = byId[tgtEdge.to]._row;
                // Find next available row starting from target row
                while (usedRows.has(targetRow)) targetRow++;
                src._row = targetRow;
                usedRows.add(targetRow);
            } else {
                // No target edge — keep original row but avoid conflicts
                let row = src._row;
                while (usedRows.has(row)) row++;
                src._row = row;
                usedRows.add(row);
            }
        });
    }

    // --- 6. Compute pixel positions ---
    content.forEach(n => {
        let stW = 120, stH = 50;
        
        if (typeof COMPOUND_STENCILS !== 'undefined' && COMPOUND_STENCILS[n.type]) {
            const template = COMPOUND_STENCILS[n.type];
            const wMatch = template.match(/width="([0-9.]+)"/);
            const hMatch = template.match(/height="([0-9.]+)"/);
            if (wMatch) stW = parseFloat(wMatch[1]);
            if (hMatch) stH = parseFloat(hMatch[1]);
        } else {
            const st = STENCILS[n.type] || STENCILS['default'];
            stW = (st.w === 'auto') ? 120 : st.w;
            stH = (st.h === 'auto') ? 50  : st.h;
        }

        n._w = stW;
        n._h = stH;

        if (n._col === -1) {
            n._x = L.leftMargin + (L.sourceColW - n._w) / 2;
        } else {
            const colX = L.leftMargin + L.sourceColW + n._col * L.phaseColW;
            n._x = colX + (L.phaseColW - n._w) / 2;
        }
        n._y = L.contentY + n._row * L.rowH;
    });

    // --- 6.5. Compute Boundary bounding boxes & rel positions ---
    L.boundaryPadding = 30; // padding inside boundary

    const boundaryDepth = (n) => {
        let nParent = byId[n.parent];
        if (nParent && nParent.type && nParent.type.startsWith('boundary')) {
            return 1 + boundaryDepth(nParent);
        }
        return 0;
    };
    
    // Sort boundaries from inner to outer based on nesting depth
    boundaries.sort((a, b) => boundaryDepth(b) - boundaryDepth(a));
    
    boundaries.forEach(b => {
        const children = allNodes.filter(c => c.parent === b.id);
        let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
        children.forEach(c => {
            if (c._x !== undefined && c._w !== undefined) {
                 minX = Math.min(minX, c._x);
                 minY = Math.min(minY, c._y);
                 maxX = Math.max(maxX, c._x + c._w);
                 maxY = Math.max(maxY, c._y + c._h);
            }
        });
        
        if (minX !== Infinity) {
            b._x = minX - L.boundaryPadding;
            b._y = minY - L.boundaryPadding - 20; // Extra top padding for boundary title
            b._w = (maxX - minX) + (L.boundaryPadding * 2);
            b._h = (maxY - minY) + (L.boundaryPadding * 2) + 20;
        } else {
            // Default blank boundary fallback if it has no children
            b._x = 0; b._y = 0; b._w = 150; b._h = 100;
        }
    });

    // Convert absolute positions relative to parent boundary
    allNodes.forEach(n => {
        if (n.parent && byId[n.parent] && byId[n.parent].type.startsWith('boundary')) {
            const p = byId[n.parent];
            if (p._x !== undefined && n._x !== undefined) {
               n._rel_x = n._x - p._x;
               n._rel_y = n._y - p._y;
            }
        }
    });
    
    // Apply relative positions
    allNodes.forEach(n => {
        if (n._rel_x !== undefined) {
            n._x = n._rel_x;
            n._y = n._rel_y;
        }
    });

    // --- 7. Generate XML ---
    let nid = 100;
    let xml = '';

    // Phase column headers
    phases.forEach((p, i) => {
        const x = L.leftMargin + L.sourceColW + i * L.phaseColW;
        xml += mxVertex(nid++, esc(p.name),
            'text;html=1;align=center;verticalAlign=middle;strokeColor=none;fillColor=none;fontSize=13;fontStyle=1;fontColor=#333333;',
            x, L.headerY, L.phaseColW, L.headerH);
    });

    // Content nodes
    const cellMap = {};
    boundaries.forEach(b => { cellMap[b.id] = nid++; });
    content.forEach(n => { cellMap[n.id] = nid++; });

    boundaries.forEach(b => {
        const cid = cellMap[b.id];
        const st = STENCILS[b.type] || STENCILS['default'];
        const pId = (b.parent && cellMap[b.parent]) ? cellMap[b.parent] : 1;
        xml += mxVertex(cid, esc(b.name), st.style, b._x, b._y, b._w, b._h, pId);
    });

    content.forEach(n => {
        const cid = cellMap[n.id];
        const pId = (n.parent && cellMap[n.parent]) ? cellMap[n.parent] : 1;

        if (typeof COMPOUND_STENCILS !== 'undefined' && COMPOUND_STENCILS[n.type]) {
            let template = COMPOUND_STENCILS[n.type];
            let idMap = {};
            let ids = [...template.matchAll(/id="([^"]+)"/g)].map(m => m[1]);
            if (ids.length > 0) {
                // Ensure the root group receives exactly the engine's edge connection ID
                idMap[ids[0]] = cid;
                for(let i=1; i<ids.length; i++) {
                    idMap[ids[i]] = cid + "_" + ids[i];
                }
            }
            
            // Map ids safely
            let outXml = template.replace(/id="([^"]+)"/g, (match, p1) => `id="${idMap[p1]}"`);
            outXml = outXml.replace(/parent="([^"]+)"/g, (match, p1) => {
                // 1 and 0 represent the root layer inside the library files, redirect to our actual parent
                if (p1 === "1" || p1 === "0") return `parent="${pId}"`;
                if (idMap[p1]) return `parent="${idMap[p1]}"`;
                return match;
            });
            
            // Instead of putting value on the root group (which causes Drawio to auto-scale children to fit text bounds),
            // we create a separate text child positioned precisely at the bottom center of the group container.
            const labelId = cid + "_label";
            const lw = 200; // Provide wide bounding rect for arbitrary text length
            const lx = (n._w - lw) / 2; // Center horizontally
            const ly = n._h; // Position exactly at the bottom border of the root group
            
            // Append the child text label to the template output
            const textNode = `<mxCell id="${labelId}" value="${esc(n.name)}" style="text;html=1;align=center;verticalAlign=top;whiteSpace=wrap;rounded=0;strokeColor=none;fillColor=none;fontColor=#333333;fontSize=11;fontStyle=1;" vertex="1" parent="${cid}"><mxGeometry x="${lx}" y="${ly}" width="${lw}" height="30" as="geometry"/></mxCell>`;
            outXml += textNode;
            
            // Inject coordinate positions x and y into the root bounds
            let geomReplaced = false;
            outXml = outXml.replace(/<mxGeometry(.*?)as="geometry"/, (match, inner) => {
                if (geomReplaced) return match;
                geomReplaced = true;
                let cleanInner = inner.replace(/\s*x="[^"]*"/, '').replace(/\s*y="[^"]*"/, '');
                return `<mxGeometry x="${n._x}" y="${n._y}" ${cleanInner} as="geometry"`;
            });
            
            xml += outXml;
        } else {
            const st = STENCILS[n.type] || STENCILS['default'];
            xml += mxVertex(cid, esc(n.name), st.style, n._x, n._y, n._w, n._h, pId);
        }
    });

    // Edges with optional green step badges
    edges.forEach(e => {
        const eid = nid++;
        const sid = cellMap[e.from];
        const tid = cellMap[e.to];
        if (!sid || !tid) return;

        let style = 'edgeStyle=orthogonalEdgeStyle;rounded=1;html=1;strokeColor=#333333;strokeWidth=1.5;';
        if (e.step) {
            style += 'labelBackgroundColor=#107c41;fontColor=#ffffff;fontSize=11;fontStyle=1;';
        }
        xml += mxEdge(eid, e.step || '', style, sid, tid);
    });

    return '<mxGraphModel><root><mxCell id="0"/><mxCell id="1" parent="0"/>' + xml + '</root></mxGraphModel>';
}

// ---- XML element helpers ----
function mxVertex(id, value, style, x, y, w, h, parentId = 1) {
    return '<mxCell id="' + id + '" value="' + value + '" style="' + style +
           '" vertex="1" parent="' + parentId + '"><mxGeometry x="' + x + '" y="' + y +
           '" width="' + w + '" height="' + h + '" as="geometry"/></mxCell>';
}

function mxEdge(id, value, style, source, target) {
    return '<mxCell id="' + id + '" value="' + value + '" style="' + style +
           '" edge="1" source="' + source + '" target="' + target +
           '" parent="1"><mxGeometry relative="1" as="geometry"/></mxCell>';
}

function esc(str) {
    return str.replace(/&/g, '&amp;').replace(/</g, '&lt;')
              .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function csvSplit(line) {
    const result = [];
    let cur = '';
    let inQ = false;
    for (const ch of line) {
        if (ch === '"') { inQ = !inQ; }
        else if (ch === ',' && !inQ) { result.push(cur); cur = ''; }
        else { cur += ch; }
    }
    result.push(cur);
    return result;
}
